/**
 * Generates src/embedded/assets.gen.ts: one `with { type: "file" }` import per
 * file of the frontend build (game-web/dist), so `bun build --compile` embeds
 * the whole game page into the server binary.
 *
 * Without a frontend build an empty manifest is written — the server then
 * only serves the API (as in development, where Vite serves the page).
 *
 * Usage: bun scripts/gen-assets.ts
 */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, relative, sep } from "path";

const backendDir = join(import.meta.dir, "..");
const distDir = join(backendDir, "..", "game-web", "dist");
const outDir = join(backendDir, "src", "embedded");
const outFile = join(outDir, "assets.gen.ts");

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    if (name.startsWith(".")) return []; // .DS_Store & co.
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

// Source maps are not needed in production
const files = existsSync(distDir) ? walk(distDir).filter((f) => !f.endsWith(".map")).sort() : [];
const lines = [
  "// Generated by scripts/gen-assets.ts — do not edit, not checked in.",
  "// Maps URL paths of the game page to files embedded in the binary.",
  "/* eslint-disable */",
];
const entries: string[] = [];
files.forEach((file, i) => {
  const importPath = relative(outDir, file).split(sep).join("/");
  const urlPath = "/" + relative(distDir, file).split(sep).join("/");
  lines.push(`import f${i} from ${JSON.stringify(importPath)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: f${i},`);
});
lines.push("", "export const assets: Record<string, string> = {", ...entries, "};", "");

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join("\n"));
console.log(`assets.gen.ts: ${files.length} files${files.length === 0 ? " (no frontend build found)" : ""}`);
